// Zaparoo Frontend
// Copyright (c) 2026 Wizzo Pty Ltd and the Zaparoo Project contributors.
// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0

#![allow(
    clippy::panic,
    clippy::expect_used,
    reason = "build scripts communicate failure by panicking; there is no richer channel to cargo"
)]

use std::fmt::Write as _;

fn main() {
    // Every `assets/systems/<id>.png` and `assets/systems-color/<id>.png`
    // becomes an `include_bytes!` entry, so the binary carries the logo art
    // itself and ships as one file. See `src/system_logos.rs`.
    embed_logo_table("systems", "system_logos_table.rs", "EMBEDDED_LOGOS");
    embed_logo_table(
        "systems-color",
        "system_color_logos_table.rs",
        "EMBEDDED_COLOR_LOGOS",
    );
    // One configuration for every target: fonts imported by the .slint
    // files are embedded as files and registered with the runtime font
    // stack on startup (see `src/fonts.rs`), on MiSTer as on the desktop.
    // The MiSTer build used to pre-render glyphs here at a fixed size
    // ladder (`EmbedForSoftwareRenderer`); that path has no text shaping.
    // Translations are bundled from translations/<lang>/LC_MESSAGES/
    // frontend.po (the file name is the crate name, which Slint uses as
    // the gettext domain) and selected at runtime by `apply_language` in
    // main.rs. No default context: one msgid is one entry, so identical
    // source strings share one translation across components.
    let config = slint_build::CompilerConfiguration::new()
        .with_bundled_translations("translations")
        .with_default_translation_context(slint_build::DefaultTranslationContext::None);
    slint_build::compile_with_config("ui/app.slint", config)
        .unwrap_or_else(|e| panic!("slint compile failed: {e}"));
}

/// Writes `$OUT_DIR/<table_file>`: every `assets/<subdir>/<id>.png` as
/// `include_bytes!`, sorted by id, as `pub static <table_name>`.
fn embed_logo_table(subdir: &str, table_file: &str, table_name: &str) {
    let manifest_dir = std::path::PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"),
    );
    let out_dir = std::path::PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    let logos_dir = manifest_dir.join("assets").join(subdir);
    println!("cargo:rerun-if-changed={}", logos_dir.display());
    let mut logos: Vec<(String, std::path::PathBuf)> = std::fs::read_dir(&logos_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", logos_dir.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "png"))
        .map(|path| {
            let id = path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .expect("png file stem")
                .to_string();
            (id, path)
        })
        .collect();
    logos.sort();
    let mut table = format!(
        "/// System id to embedded PNG bytes, sorted by id (generated by build.rs).\n\
         pub static {table_name}: &[(&str, &[u8])] = &[\n",
    );
    for (id, path) in &logos {
        println!("cargo:rerun-if-changed={}", path.display());
        let _ = writeln!(
            table,
            "    ({id:?}, include_bytes!({:?})),",
            path.display().to_string()
        );
    }
    table.push_str("];\n");
    std::fs::write(out_dir.join(table_file), table)
        .unwrap_or_else(|e| panic!("write {table_file}: {e}"));
}
