#!/usr/bin/env bash
# Zaparoo Frontend
# Copyright (c) 2026 Wizzo Pty Ltd and the Zaparoo Project contributors.
# SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
#
# Cheap staleness check on resources/baked/icons.zbin: does the committed
# manifest list exactly the SVGs in the tree, with matching hashes?
#
# Deliberately pure coreutils — no Qt, no build — so it runs on any host and in
# any container. Diffing two sorted "path sha" lists catches added, removed and
# modified sources symmetrically. It cannot catch "the SVG is unchanged but the
# bake came from a different Qt"; tests/tst_baked_icon_atlas.cpp and
# `bake-icons --verify` cover that.
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
repo_root="$(cd -- "$script_dir/.." && pwd -P)"
manifest="$repo_root/resources/baked/icons.manifest"
blob="$repo_root/resources/baked/icons.zbin"

fail() {
    echo "$1" >&2
    echo "Run \`just bake-icons\` and commit resources/baked/." >&2
    exit 1
}

[[ -f "$manifest" ]] || fail "Missing $manifest."
[[ -f "$blob" ]] || fail "Missing $blob."

actual="$(mktemp)"
expected="$(mktemp)"
trap 'rm -f "$actual" "$expected"' EXIT

(
    cd "$repo_root/resources"
    find images/systems images/categories images/icons images/status -name '*.svg' -type f -print0 |
        sort -z | xargs -0 sha256sum | awk '{ print $2, $1 }'
) | sort >"$actual"

# Skip the `# comment` and `key value` preamble; asset lines are the ones whose
# first field is a path under images/. Corner masks (images/corners/cut-*) are
# procedurally generated by the bake tool, not sourced from an SVG in the
# tree, so they have no counterpart to diff against here.
awk '$1 ~ /^images\// && $1 !~ /^images\/corners\// { print $1, $2 }' "$manifest" | sort >"$expected"

if ! diff -u "$expected" "$actual" >/dev/null; then
    echo "Baked icon atlas is stale. Differences (expected = manifest, actual = tree):" >&2
    diff -u --label manifest --label tree "$expected" "$actual" >&2 || true
    fail "resources/baked/icons.manifest does not match resources/images/."
fi
